package sqlstore

const InsertQ = "insert into "
const SelectQ = "select * from "
const DeleteQ = "delete from "
const UpdateQ = "update "

const UsersT = "users "
const SkillsT = "skills "
const SkillCategoriesT = "skill_categories "
const RacesT = "races "
const CharacterClassT = "character_classes "
const ActionsT = "actions "
const RaceBonusesT = "race_bonuses "
const CharacterClassBonusesT = "character_class_bonuses "
const SystemT = "system "
const SystemRacesT = "system_races "
const SystemClassesT = "system_classes "
const SystemSkillsT = "system_skills "

const UsersP = "(email, nickname, encrypted_password) "
const SkillsP = "(name, icon, category_id) "
const SkillCategoriesP = "(name, icon) "
const RacesP = "(name, model) "
const CharacterClassesP = "(name, icon) "
const ActionsP = "(name, icon, skill_id, points) "
const RaceBonusesP = "(race_id, skill_id, bonus) "
const CharacterClassBonusesP = "(class_id, skill_id, bonus) "
const SystemP = "(system) "
const SystemRacesP = "(system_races) "
const SystemClassesP = "(system_classes) "
const SystemSkillsP = "(system_skills) "
