package sqlstore

const InsertQ = "insert into "
const SelectQ = "select * from "
const DeleteQ = "delete from "
const UpdateQ = "update "

const UsersT = "users "
const CharacteristicsT = "Characteristics "
const SkillsT = "skills "
const SkillCategoriesT = "skill_categories "
const RacesT = "races "
const CharacterClassT = "character_classes "
const ActionsT = "actions "
const RaceBonusesT = "race_bonuses "
const CharacterClassBonusesT = "character_class_bonuses "
const SystemsT = "game_systems "
const SystemRacesT = "game_system_races "
const SystemClassesT = "game_system_classes "
const SystemSkillsT = "game_system_skills "
const SystemActionsT = "game_system_actions "

const UsersP = "(email, nickname, encrypted_password) "
const CharacteristicsP = "(name, icon, user_id) "
const SkillsP = "(name, icon, category_id, characteristic_id, user_id) "
const SkillCategoriesP = "(name, icon, user_id) "
const RacesP = "(name, model, user_id) "
const CharacterClassesP = "(name, icon, user_id) "
const ActionsP = "(name, icon, skill_id, points, user_id) "
const RaceBonusesP = "(race_id, skill_id, bonus) "
const CharacterClassBonusesP = "(class_id, skill_id, bonus) "
const SystemsP = "(id, icon, name, user_id) "
const SystemRacesP = "(system_id, race_id) "
const SystemClassesP = "(system_id, class_id) "
const SystemSkillsP = "(system_id, skill_id) "
const SystemActionsP = "(system_id, action_id) "
