CREATE TABLE IF NOT EXISTS Actions
(
    id integer NOT NULL GENERATED ALWAYS AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 0 MAXVALUE 2147483646 CACHE 1 ),
    name VARCHAR(255) NOT NULL,
    icon VARCHAR(1024),
    skill_id INTEGER,
    points INTEGER NOT NULL,
    user_id INTEGER NOT NULL REFERENCES users(id) ON DELETE cascade,

    CONSTRAINT Actions_pkey PRIMARY KEY (id),
    FOREIGN KEY (skill_id) REFERENCES Skills(id) ON DELETE SET NULL
);
