CREATE TABLE IF NOT EXISTS Character_Classes
(
    id integer NOT NULL GENERATED ALWAYS AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 0 MAXVALUE 2147483646 CACHE 1 ),
    name VARCHAR(255) NOT NULL,
    icon VARCHAR(1024),
    user_id INTEGER NOT NULL REFERENCES users(id) ON DELETE cascade,

    CONSTRAINT Character_Classes_pkey PRIMARY KEY (id)
);