package db

const insertQ = "insert into "
const selectQ = "select * from "
const deleteQ = "delete from "
const updateQ = "update "

const skillsT = "skills "
const skillsCategoryT = "skill_categories "
const racesT = "races "
const characterClassT = "character_classes "
const actionsT = "actions "
const raceBonusesT = "race_bonuses "
const characterClassBonusesT = "character_class_bonuses "
const systemT = "system "
const systemRacesT = "system_races "
const systemClassesT = "system_classes "
const systemSkillsT = "system_skills "

const skillsP = "(name, icon, category_id) "
const skillCategoriesP = "(name, icon) "
const racesP = "name, model "
const characterClassesP = "name, icon "
const actionsP = "actions "
const raceBonusesP = "race_bonuses "
const characterClassBonusesP = "character_class_bonuses "
const systemP = "system "
const systemRacesP = "system_races "
const systemClassesP = "system_classes "
const systemSkillsP = "system_skills "
